# Generated by Django 4.2 on 2023-04-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='lng',
        ),
    ]
